import json
import math

def generate_molecules_data():
    # Helper to calculate bond length
    def dist(a, b):
        return math.sqrt((a['x']-b['x'])**2 + (a['y']-b['y'])**2 + (a['z']-b['z'])**2)

    # 50 molecules definitions
    molecules = [
        # GROUP 1: Hydrocarbon no (Alkane & Xicloankan)
        {
            "id": "methane",
            "name": "Methane (Metan)",
            "iupac": "Methane",
            "formula": "CH4",
            "condensed": "CH4",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 16.04,
            "geometry": "Tứ diện đều (Tetrahedral)",
            "hybridization": "sp³",
            "state": "Khí không màu, không mùi",
            "boilingPoint": "-161.5 °C",
            "meltingPoint": "-182.5 °C",
            "solubility": "Thực tế không tan trong nước, tan trong dung môi hữu cơ",
            "reactions": "Phản ứng thế Halogen (CH₄ + Cl₂ → CH₃Cl + HCl), phản ứng cháy (CH₄ + 2O₂ → CO₂ + 2H₂O), phản ứng nhiệt phân tạo C₂H₂ (1500°C làm lạnh nhanh).",
            "applications": "Thành phần chính của khí thiên nhiên, khí mỏ dầu và Biogas; làm nhiên liệu sạch cho gia đình và công nghiệp, nguyên liệu sản xuất phân đạm và hydro.",
            "description": "Methane là hydrocacbon đơn giản nhất, là thành viên đầu tiên của dãy đồng đẳng ankan.",
            "atoms": [
                {"element": "C", "x": 0.0, "y": 0.0, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": 0.629, "y": 0.629, "z": 0.629, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -0.629, "y": -0.629, "z": 0.629, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -0.629, "y": 0.629, "z": -0.629, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.629, "y": -0.629, "z": -0.629, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 0, "a2": 2, "order": 1},
                {"a1": 0, "a2": 3, "order": 1},
                {"a1": 0, "a2": 4, "order": 1}
            ]
        },
        {
            "id": "ethane",
            "name": "Ethane (Etan)",
            "iupac": "Ethane",
            "formula": "C2H6",
            "condensed": "CH3-CH3",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 30.07,
            "geometry": "2 Tứ diện lồng vào nhau",
            "hybridization": "sp³",
            "state": "Khí không màu, không mùi, dễ cháy",
            "boilingPoint": "-88.6 °C",
            "meltingPoint": "-182.8 °C",
            "solubility": "Rất ít tan trong nước, tan tốt trong ete, benzen",
            "reactions": "Phản ứng thế clo (C₂H₆ + Cl₂ → C₂H₅Cl + HCl), phản ứng đề hidro hóa thành etilen (C₂H₆ → C₂H₄ + H₂).",
            "applications": "Dùng trong công nghiệp hóa dầu để sản xuất ethylene qua phản ứng nhiệt phân crăckinh hơi nước.",
            "description": "Ethane là ankan 2 carbon với liên kết đơn C-C có khả năng quay tự do quanh trục.",
            "atoms": [
                {"element": "C", "x": -0.77, "y": 0.0, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.77, "y": 0.0, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": -1.16, "y": 1.02, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.16, "y": -0.51, "z": 0.89, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.16, "y": -0.51, "z": -0.89, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.16, "y": -1.02, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.16, "y": 0.51, "z": -0.89, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.16, "y": 0.51, "z": 0.89, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 0, "a2": 2, "order": 1},
                {"a1": 0, "a2": 3, "order": 1},
                {"a1": 0, "a2": 4, "order": 1},
                {"a1": 1, "a2": 5, "order": 1},
                {"a1": 1, "a2": 6, "order": 1},
                {"a1": 1, "a2": 7, "order": 1}
            ]
        },
        {
            "id": "propane",
            "name": "Propane (Propan)",
            "iupac": "Propane",
            "formula": "C3H8",
            "condensed": "CH3-CH2-CH3",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 44.10,
            "geometry": "Mạch gấp khúc góc 109.5°",
            "hybridization": "sp³",
            "state": "Khí không màu, dễ hóa lỏng dưới áp suất",
            "boilingPoint": "-42.1 °C",
            "meltingPoint": "-187.7 °C",
            "solubility": "Không tan trong nước, hòa tan trong cồn, ete",
            "reactions": "Cháy hoàn toàn sinh lượng nhiệt lớn (C₃H₈ + 5O₂ → 3CO₂ + 4H₂O), thế thế bậc 2 ưu tiên theo quy tắc.",
            "applications": "Thành phần chủ đạo trong khí dầu mỏ hóa lỏng (LPG / Gas đun nấu), nhiên liệu động cơ xe sạch, tác nhân làm lạnh.",
            "description": "Propane là ankan 3 carbon được ứng dụng phổ biến nhất làm nhiên liệu sạch gia dụng.",
            "atoms": [
                {"element": "C", "x": 0.0, "y": 0.58, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -1.26, "y": -0.29, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 1.26, "y": -0.29, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": 0.0, "y": 1.24, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 1.24, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -2.16, "y": 0.33, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.30, "y": -0.93, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.30, "y": -0.93, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.16, "y": 0.33, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.30, "y": -0.93, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.30, "y": -0.93, "z": 0.88, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 0, "a2": 2, "order": 1},
                {"a1": 0, "a2": 3, "order": 1},
                {"a1": 0, "a2": 4, "order": 1},
                {"a1": 1, "a2": 5, "order": 1},
                {"a1": 1, "a2": 6, "order": 1},
                {"a1": 1, "a2": 7, "order": 1},
                {"a1": 2, "a2": 8, "order": 1},
                {"a1": 2, "a2": 9, "order": 1},
                {"a1": 2, "a2": 10, "order": 1}
            ]
        },
        {
            "id": "butane",
            "name": "Butane (Butan)",
            "iupac": "Butane",
            "formula": "C4H10",
            "condensed": "CH3-CH2-CH2-CH3",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 58.12,
            "geometry": "Mạch zic-zắc không nhánh",
            "hybridization": "sp³",
            "state": "Khí không màu, dễ hóa lỏng",
            "boilingPoint": "-0.5 °C",
            "meltingPoint": "-138.4 °C",
            "solubility": "Kém tan trong nước, tan tốt trong cloroform",
            "reactions": "Oxi hóa hoàn toàn và không hoàn toàn tạo axit axetic, phản ứng craking tạo metan, etilen, propan.",
            "applications": "Nhiên liệu bật lửa gas, bếp gas du lịch, thành phần chính của khí đốt LPG.",
            "description": "Butane mạch thẳng có nhiệt độ sôi xấp xỉ 0°C, cực kỳ tiện lợi cho bình gas nén mini.",
            "atoms": [
                {"element": "C", "x": -1.90, "y": -0.36, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -0.63, "y": 0.49, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.63, "y": -0.49, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 1.90, "y": 0.36, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": -2.81, "y": 0.25, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.94, "y": -1.00, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.94, "y": -1.00, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -0.63, "y": 1.14, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -0.63, "y": 1.14, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.63, "y": -1.14, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.63, "y": -1.14, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.81, "y": -0.25, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.94, "y": 1.00, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.94, "y": 1.00, "z": -0.88, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 1, "a2": 2, "order": 1},
                {"a1": 2, "a2": 3, "order": 1},
                {"a1": 0, "a2": 4, "order": 1},
                {"a1": 0, "a2": 5, "order": 1},
                {"a1": 0, "a2": 6, "order": 1},
                {"a1": 1, "a2": 7, "order": 1},
                {"a1": 1, "a2": 8, "order": 1},
                {"a1": 2, "a2": 9, "order": 1},
                {"a1": 2, "a2": 10, "order": 1},
                {"a1": 3, "a2": 11, "order": 1},
                {"a1": 3, "a2": 12, "order": 1},
                {"a1": 3, "a2": 13, "order": 1}
            ]
        },
        {
            "id": "isobutane",
            "name": "Isobutane (Isobutan)",
            "iupac": "2-Methylpropane",
            "formula": "C4H10",
            "condensed": "CH(CH3)3",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 58.12,
            "geometry": "Phân nhánh 3 nhánh chóp tam giác",
            "hybridization": "sp³",
            "state": "Khí không màu",
            "boilingPoint": "-11.7 °C",
            "meltingPoint": "-159.6 °C",
            "solubility": "Không tan trong nước",
            "reactions": "Phản ứng thế ưu tiên vị trí C bậc 3, phản ứng dehydro hóa thành isobutene.",
            "applications": "Môi chất lạnh thân thiện tầng ozone (R600a) trong tủ lạnh hiện đại, khí đẩy bình xịt bọt cạo râu.",
            "description": "Đồng phân phân nhánh của butan với nguyên tử Carbon bậc 3 ở trung tâm.",
            "atoms": [
                {"element": "C", "x": 0.0, "y": 0.0, "z": 0.36, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.0, "y": 1.45, "z": -0.19, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -1.26, "y": -0.73, "z": -0.19, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 1.26, "y": -0.73, "z": -0.19, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": 0.0, "y": 0.0, "z": 1.45, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 2.27, "z": 0.54, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.88, "y": 1.57, "z": -0.83, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -0.88, "y": 1.57, "z": -0.83, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -2.16, "y": -0.21, "z": 0.16, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.28, "y": -1.74, "z": 0.22, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.30, "y": -0.78, "z": -1.28, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.16, "y": -0.21, "z": 0.16, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.28, "y": -1.74, "z": 0.22, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.30, "y": -0.78, "z": -1.28, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 0, "a2": 2, "order": 1},
                {"a1": 0, "a2": 3, "order": 1},
                {"a1": 0, "a2": 4, "order": 1},
                {"a1": 1, "a2": 5, "order": 1},
                {"a1": 1, "a2": 6, "order": 1},
                {"a1": 1, "a2": 7, "order": 1},
                {"a1": 2, "a2": 8, "order": 1},
                {"a1": 2, "a2": 9, "order": 1},
                {"a1": 2, "a2": 10, "order": 1},
                {"a1": 3, "a2": 11, "order": 1},
                {"a1": 3, "a2": 12, "order": 1},
                {"a1": 3, "a2": 13, "order": 1}
            ]
        },
        {
            "id": "pentane",
            "name": "Pentane (Pentan)",
            "iupac": "Pentane",
            "formula": "C5H12",
            "condensed": "CH3-(CH2)3-CH3",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 72.15,
            "geometry": "Mạch zic-zắc 5 carbon",
            "hybridization": "sp³",
            "state": "Chất lỏng không màu, dễ bay hơi",
            "boilingPoint": "36.1 °C",
            "meltingPoint": "-129.8 °C",
            "solubility": "Không tan trong nước, trộn lẫn vô hạn với xăng, ete",
            "reactions": "Cháy tỏa nhiệt, cracking xúc tác tạo ankan và anken ngắn hơn.",
            "applications": "Dung môi hữu cơ phòng thí nghiệm, tác nhân tạo bọt xốp polystyrene (EPS), thành phần xăng.",
            "description": "Pentane là ankan mạch thẳng đầu tiên ở trạng thái lỏng tại nhiệt độ phòng.",
            "atoms": [
                {"element": "C", "x": -2.54, "y": 0.35, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -1.27, "y": -0.49, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.0, "y": 0.35, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 1.27, "y": -0.49, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 2.54, "y": 0.35, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": -3.44, "y": -0.27, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -2.58, "y": 1.00, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -2.58, "y": 1.00, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.27, "y": -1.14, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.27, "y": -1.14, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 1.00, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 1.00, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.27, "y": -1.14, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.27, "y": -1.14, "z": -0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 3.44, "y": -0.27, "z": 0.0, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.58, "y": 1.00, "z": 0.88, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.58, "y": 1.00, "z": -0.88, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 1, "a2": 2, "order": 1},
                {"a1": 2, "a2": 3, "order": 1},
                {"a1": 3, "a2": 4, "order": 1},
                {"a1": 0, "a2": 5, "order": 1},
                {"a1": 0, "a2": 6, "order": 1},
                {"a1": 0, "a2": 7, "order": 1},
                {"a1": 1, "a2": 8, "order": 1},
                {"a1": 1, "a2": 9, "order": 1},
                {"a1": 2, "a2": 10, "order": 1},
                {"a1": 2, "a2": 11, "order": 1},
                {"a1": 3, "a2": 12, "order": 1},
                {"a1": 3, "a2": 13, "order": 1},
                {"a1": 4, "a2": 14, "order": 1},
                {"a1": 4, "a2": 15, "order": 1},
                {"a1": 4, "a2": 16, "order": 1}
            ]
        },
        {
            "id": "cyclopropane",
            "name": "Cyclopropane (Xiclopropan)",
            "iupac": "Cyclopropane",
            "formula": "C3H6",
            "condensed": "c-C3H6 (Vòng 3 cạnh)",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 42.08,
            "geometry": "Tam giác đều phẳng có sức căng vòng lớn (góc 60°)",
            "hybridization": "sp³ (biến dạng góc liên kết 'banana bond')",
            "state": "Khí không màu, mùi thơm ngọt",
            "boilingPoint": "-32.9 °C",
            "meltingPoint": "-127.6 °C",
            "solubility": "Ít tan trong nước, tan tốt trong ete",
            "reactions": "Dễ mở vòng phản ứng cộng với H₂, Br₂, HBr do sức căng Baeyer rất lớn (khác với ankan thông thường).",
            "applications": "Từng dùng làm thuốc gây mê qua đường thở an toàn trong y học, dùng nghiên cứu cấu trúc liên kết hóa học uốn cong.",
            "description": "Vòng xicloankan nhỏ nhất với góc liên kết 60°, mang tính chất phản ứng cộng mở vòng độc đáo.",
            "atoms": [
                {"element": "C", "x": 0.0, "y": 0.87, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -0.76, "y": -0.44, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.76, "y": -0.44, "z": 0.0, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": 0.0, "y": 1.48, "z": 0.90, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 1.48, "z": -0.90, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.31, "y": -0.74, "z": 0.90, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.31, "y": -0.74, "z": -0.90, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.31, "y": -0.74, "z": 0.90, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.31, "y": -0.74, "z": -0.90, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 1, "a2": 2, "order": 1},
                {"a1": 2, "a2": 0, "order": 1},
                {"a1": 0, "a2": 3, "order": 1},
                {"a1": 0, "a2": 4, "order": 1},
                {"a1": 1, "a2": 5, "order": 1},
                {"a1": 1, "a2": 6, "order": 1},
                {"a1": 2, "a2": 7, "order": 1},
                {"a1": 2, "a2": 8, "order": 1}
            ]
        },
        {
            "id": "cyclopentane",
            "name": "Cyclopentane (Xiclopentan)",
            "iupac": "Cyclopentane",
            "formula": "C5H10",
            "condensed": "c-C5H10 (Vòng 5 cạnh)",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 70.13,
            "geometry": "Dạng phong bì (Envelope conformation)",
            "hybridization": "sp³",
            "state": "Chất lỏng không màu, mùi tựa xăng",
            "boilingPoint": "49.2 °C",
            "meltingPoint": "-93.9 °C",
            "solubility": "Không tan trong nước",
            "reactions": "Chủ yếu phản ứng thế tương tự ankan, bền vững không mở vòng với Br₂ ở điều kiện thường.",
            "applications": "Chất trợ nở sản xuất mút cách nhiệt tủ lạnh và vật liệu xây dựng polyurethane, dung môi chiết xuất.",
            "description": "Vòng 5 carbon linh hoạt cấu dạng phong bì để giảm lực đẩy giữa các liên kết C-H.",
            "atoms": [
                {"element": "C", "x": 0.0, "y": 1.25, "z": 0.15, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 1.19, "y": 0.38, "z": -0.10, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.73, "y": -1.02, "z": 0.12, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -0.73, "y": -1.02, "z": -0.12, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -1.19, "y": 0.38, "z": 0.10, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": 0.0, "y": 2.05, "z": -0.60, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 1.68, "z": 1.15, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.52, "y": 0.44, "z": -1.14, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.06, "y": 0.65, "z": 0.51, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.23, "y": -1.78, "z": -0.49, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.89, "y": -1.29, "z": 1.17, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.23, "y": -1.78, "z": 0.49, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -0.89, "y": -1.29, "z": -1.17, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.52, "y": 0.44, "z": 1.14, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -2.06, "y": 0.65, "z": -0.51, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 1, "a2": 2, "order": 1},
                {"a1": 2, "a2": 3, "order": 1},
                {"a1": 3, "a2": 4, "order": 1},
                {"a1": 4, "a2": 0, "order": 1},
                {"a1": 0, "a2": 5, "order": 1},
                {"a1": 0, "a2": 6, "order": 1},
                {"a1": 1, "a2": 7, "order": 1},
                {"a1": 1, "a2": 8, "order": 1},
                {"a1": 2, "a2": 9, "order": 1},
                {"a1": 2, "a2": 10, "order": 1},
                {"a1": 3, "a2": 11, "order": 1},
                {"a1": 3, "a2": 12, "order": 1},
                {"a1": 4, "a2": 13, "order": 1},
                {"a1": 4, "a2": 14, "order": 1}
            ]
        },
        {
            "id": "cyclohexane",
            "name": "Cyclohexane (Xiclohexan)",
            "iupac": "Cyclohexane",
            "formula": "C6H12",
            "condensed": "c-C6H12 (Vòng 6 cạnh)",
            "group": "Hydrocarbon no",
            "groupId": "alkane",
            "molarMass": 84.16,
            "geometry": "Cấu dạng ghế bền vững (Chair conformation)",
            "hybridization": "sp³",
            "state": "Chất lỏng không màu, không phân cực",
            "boilingPoint": "80.7 °C",
            "meltingPoint": "6.5 °C",
            "solubility": "Không tan trong nước, hòa tan chất béo, dầu mỡ",
            "reactions": "Phản ứng thế halogen (chiếu sáng), oxi hóa tạo axit adipic sản xuất nilon-6,6.",
            "applications": "Dung môi không phân cực kinh điển, nguyên liệu công nghiệp điều chế caprolactam và axit adipic sản xuất sợi tổng hợp nilon.",
            "description": "Cyclohexane có cấu dạng ghế hoàn hảo không hề có sức căng góc hay sức căng che khuất.",
            "atoms": [
                {"element": "C", "x": 1.26, "y": 0.73, "z": 0.23, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.0, "y": 1.45, "z": -0.23, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -1.26, "y": 0.73, "z": 0.23, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": -1.26, "y": -0.73, "z": -0.23, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 0.0, "y": -1.45, "z": 0.23, "hybrid": "sp³", "valency": 4},
                {"element": "C", "x": 1.26, "y": -0.73, "z": -0.23, "hybrid": "sp³", "valency": 4},
                {"element": "H", "x": 1.28, "y": 0.74, "z": 1.33, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.16, "y": 1.25, "z": -0.12, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 1.48, "z": -1.33, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": 2.49, "z": 0.12, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.28, "y": 0.74, "z": 1.33, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -2.16, "y": 1.25, "z": -0.12, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -1.28, "y": -0.74, "z": -1.33, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": -2.16, "y": -1.25, "z": 0.12, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": -1.48, "z": 1.33, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 0.0, "y": -2.49, "z": -0.12, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 1.28, "y": -0.74, "z": -1.33, "hybrid": "1s", "valency": 1},
                {"element": "H", "x": 2.16, "y": -1.25, "z": 0.12, "hybrid": "1s", "valency": 1}
            ],
            "bonds": [
                {"a1": 0, "a2": 1, "order": 1},
                {"a1": 1, "a2": 2, "order": 1},
                {"a1": 2, "a2": 3, "order": 1},
                {"a1": 3, "a2": 4, "order": 1},
                {"a1": 4, "a2": 5, "order": 1},
                {"a1": 5, "a2": 0, "order": 1},
                {"a1": 0, "a2": 6, "order": 1},
                {"a1": 0, "a2": 7, "order": 1},
                {"a1": 1, "a2": 8, "order": 1},
                {"a1": 1, "a2": 9, "order": 1},
                {"a1": 2, "a2": 10, "order": 1},
                {"a1": 2, "a2": 11, "order": 1},
                {"a1": 3, "a2": 12, "order": 1},
                {"a1": 3, "a2": 13, "order": 1},
                {"a1": 4, "a2": 14, "order": 1},
                {"a1": 4, "a2": 15, "order": 1},
                {"a1": 5, "a2": 16, "order": 1},
                {"a1": 5, "a2": 17, "order": 1}
            ]
        }
    ]
    return molecules

print("Generating script...")
